
module.exports = {
  tools: [
  {
    id: 'akiflow',
    name: 'Akiflow',
    description: 'Akiflow is a daily planner app for busy professionals for task & calendar management.',
    logo: '/logos/akiflow.png',
    link: 'https://akiflow.com',
    categories: ['daily-planners', 'todo-list', 'calendar'],
    platforms: ['mac', 'web'],
    pricing: ['subscription'],
    roles: ['manager', 'entrepreneur'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high',
    isSponsored: true
  },
  {
    id: 'tana',
    name: 'Tana',
    description: 'Tana is a powerful PKM note-taking app designed for advanced note-taking & beyond.',
    logo: '/logos/tana.png',
    link: 'https://tana.inc',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'developer'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high',
    isSponsored: true
  },
  {
    id: 'monday',
    name: 'monday',
    description: 'monday.com offers all-round project management popular with all-rounder use in teams.',
    logo: '/logos/monday.png',
    link: 'https://monday.com',
    categories: ['project-management', 'team-knowledge'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['manager', 'developer', 'operations'],
    userTypes: ['small-business', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Notion is an all-in-one workspaces for notes, projects, tasks, documents & calendar.',
    logo: '/logos/notion.png',
    link: 'https://notion.so',
    categories: ['all-in-one', 'note-taking', 'project-management'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'superhuman',
    name: 'Superhuman',
    description: 'Superhuman Email is a email app used by busy professionals for inbox management.',
    logo: '/logos/superhuman.png',
    link: 'https://superhuman.com',
    categories: ['email'],
    platforms: ['web', 'ios', 'mac'],
    pricing: ['subscription'],
    roles: ['manager', 'entrepreneur'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    description: 'ClickUp is a project management software designed for teams to collaborate & work.',
    logo: '/logos/clickup.png',
    link: 'https://clickup.com',
    categories: ['project-management', 'todo-list'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Slack is a messaging app for business that connects people to the information they need.',
    logo: '/logos/slack.png',
    link: 'https://slack.com',
    categories: ['team-communication'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows', 'linux'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Todoist is one of the best to-do list applications with all-round natured features.',
    logo: '/logos/todoist.png',
    link: 'https://todoist.com',
    categories: ['todo-list'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'craft',
    name: 'Craft',
    description: 'Craft is a personal and team documents application that creates beautiful docs.',
    logo: '/logos/craft.png',
    link: 'https://craft.do',
    categories: ['note-taking', 'document-editing'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high',
    isEditorChoice: true
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Linear helps streamline software projects, sprints, tasks, and bug tracking.',
    logo: '/logos/linear.png',
    link: 'https://linear.app',
    categories: ['project-management', 'agile-tools'],
    platforms: ['web', 'mac'],
    pricing: ['subscription'],
    roles: ['developer', 'manager'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['development'],
    customizability: 'medium'
  },
  {
    id: 'rows',
    name: 'Rows',
    description: 'Rows is a spreadsheet app designed for teams to better collaborate on data & inputs.',
    logo: '/logos/rows.png',
    link: 'https://rows.com',
    categories: ['spreadsheet'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'freshworks',
    name: 'Freshworks',
    description: 'Freshworks is a CRM software designed for customer service & relationship management.',
    logo: '/logos/freshworks.png',
    link: 'https://freshworks.com',
    categories: ['crm-software'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'sales'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['sales'],
    customizability: 'high'
  },
  {
    id: 'slite',
    name: 'Slite',
    description: 'Slite is a knowledge base for teams to share notes, documents and more.',
    logo: '/logos/slite.png',
    link: 'https://slite.com',
    categories: ['team-knowledge', 'note-taking'],
    platforms: ['web', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'lunatask',
    name: 'Lunatask',
    description: 'Lunatask is an encrypted to-do list app for habits, notes & journal entries.',
    logo: '/logos/lunatask.png',
    link: 'https://lunatask.app',
    categories: ['todo-list', 'habit-tracking', 'journaling'],
    platforms: ['mac', 'windows', 'linux'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'bitrix24',
    name: 'Bitrix24',
    description: 'Bitrix24 a free AI-powered productivity platform with 35+ business tools.',
    logo: '/logos/bitrix24.png',
    link: 'https://bitrix24.com',
    categories: ['all-in-one', 'crm-software', 'project-management'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud', 'on-premise'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'recall',
    name: 'Recall AI',
    description: 'Recall AI wants you to summarize news, docs, media for recall and organization later.',
    logo: '/logos/recall.png',
    link: 'https://recall.ai',
    categories: ['ai-tools', 'note-taking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'noteplan',
    name: 'NotePlan',
    description: 'NotePlan is a unique note-taking app with a focus on calendar and tasks in one.',
    logo: '/logos/noteplan.png',
    link: 'https://noteplan.co',
    categories: ['note-taking', 'calendar', 'todo-list'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'xtiles',
    name: 'xTiles',
    description: 'xTiles makes for managing projects and tasks with your yourself and team members.',
    logo: '/logos/xtiles.png',
    link: 'https://xtiles.app',
    categories: ['project-management', 'todo-list'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'saga',
    name: 'Saga',
    description: 'Saga.so is a clever notes and tasks app with the power of AI.',
    logo: '/logos/saga.png',
    link: 'https://saga.so',
    categories: ['note-taking', 'ai-tools'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'gqueues',
    name: 'GQueues',
    description: 'GQueues is a task manager built specifically for teams on Google Workspace.',
    logo: '/logos/gqueues.png',
    link: 'https://gqueues.com',
    categories: ['todo-list', 'project-management'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'remnote',
    name: 'RemNote',
    description: 'RemNote is an advanced note-taking app popular with students for creating flashcards.',
    logo: '/logos/remnote.png',
    link: 'https://remnote.com',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web', 'mac', 'windows', 'linux'],
    pricing: ['free', 'subscription'],
    roles: ['student'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['education'],
    customizability: 'high'
  },
  {
    id: 'scrintal',
    name: 'Scrintal',
    description: 'Scrintal wants to be a way to brainstorm your mind and capture your ideas & thoughts.',
    logo: '/logos/scrintal.png',
    link: 'https://scrintal.com',
    categories: ['mind-mapping', 'note-taking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'amplenote',
    name: 'Amplenote',
    description: 'A GTD users dream for managing notes, ranking your tasks and co-ordinating calendar.',
    logo: '/logos/amplenote.png',
    link: 'https://amplenote.com',
    categories: ['note-taking', 'gtd-tools', 'todo-list'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'reflect',
    name: 'Reflect Notes',
    description: 'Reflect Notes is a networked thought note-taking tool for notes, daily notes & tasks.',
    logo: '/logos/reflect.png',
    link: 'https://reflect.app',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'focusedos',
    name: 'focusedOS',
    description: 'focusedOS wants to be a unique tool for blocking other sites distractions on macOS.',
    logo: 'https://focusedos.com/assets/logo.png',
    link: 'https://focusedos.com',
    categories: ['focus-apps'],
    platforms: ['mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'dumbphone',
    name: 'Dumb Phone',
    description: 'Dumbphone is a way to turn your iPhone into a simple, yet focused phone.',
    logo: 'https://dumbphone.app/apple-touch-icon.png',
    link: 'https://dumbphone.app',
    categories: ['focus-apps'],
    platforms: ['ios'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'filter',
    name: 'Filter',
    description: 'Filter is a macOS designed to help you to block distractions and websites.',
    logo: '/logos/filter.png',
    link: 'https://filterapp.com',
    categories: ['focus-apps'],
    platforms: ['mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'focused-work',
    name: 'Focused Work',
    description: 'Focused Work is a pomodoro timer app to help improve focus, and get more work done.',
    logo: '/logos/focused-work.png',
    link: 'https://focusedwork.app',
    categories: ['focus-apps', 'time-tracking'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'liftos',
    name: 'liftOS',
    description: 'liftOS is a collaborative workspace for your team to better manage your workload.',
    logo: 'https://liftos.com/favicon.ico',
    link: 'https://liftos.com',
    categories: ['project-management', 'team-knowledge'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high',
    isRisingStar: true
  },
  {
    id: 'spike',
    name: 'Spike',
    description: 'Spike is an email app that handles documents, team chat, and video communication.',
    logo: '/logos/spike.png',
    link: 'https://spikenow.com',
    categories: ['email', 'team-communication'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'timestripe',
    name: 'Timestripe',
    description: 'Timestripe is a personal goal planning application with tasks & daily planning',
    logo: '/logos/timestripe.png',
    link: 'https://timestripe.com',
    categories: ['todo-list', 'daily-planners', 'habit-tracking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'workflowy',
    name: 'Workflowy',
    description: 'Workflowy is an outliner based note-taking application with a way to connect notes.',
    logo: '/logos/workflowy.png',
    link: 'https://workflowy.com',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'attentive',
    name: 'Attentive',
    description: 'Successfully reduce mindless screen time with science-backed tips and techniques. Block apps, build healthy habits, and improve your digital wellbeing.',
    logo: '/logos/attentive.png',
    link: 'https://apps.apple.com/us/app/attentive-digital-wellbeing/id1559421907?ref=toolfinder.co',
    categories: ['focus-apps', 'habit-tracking', 'mindful'],
    platforms: ['ios', 'mac', 'watch', 'vision'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'granola',
    name: 'Granola AI',
    description: 'AI-powered productivity assistant that helps streamline your workflow and tasks.',
    logo: '/logos/granola.png',
    link: 'https://granola.ai',
    categories: ['ai-tools', 'daily-planners'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high',
    isRisingStar: true
  },
  {
    id: 'setapp',
    name: 'Setapp',
    description: 'Setapp allows you to pay a monthly price and use unlimited productivity apps & tools.',
    logo: '/logos/setapp.png',
    link: 'https://setapp.com',
    categories: ['all-in-one'],
    platforms: ['mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'things3',
    name: 'Things 3',
    description: 'Things is a delightful and easy to use task manager for Apple devices.',
    logo: '/logos/things3.png',
    link: 'https://culturedcode.com/things/',
    categories: ['todo-list', 'daily-planners'],
    platforms: ['mac', 'ios'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isEditorChoice: true
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Obsidian is a powerful knowledge base that works on top of your local folder of plain text Markdown files.',
    logo: '/logos/obsidian.png',
    link: 'https://obsidian.md',
    categories: ['note-taking', 'pkm-apps', 'markdown'],
    platforms: ['mac', 'windows', 'linux', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['local'],
    industries: ['all'],
    customizability: 'high',
    isEditorChoice: true
  },
  {
    id: 'notion-calendar',
    name: 'Notion Calendar',
    description: 'Notion Calendar is a calendar app owned by Notion for managing events & meetings.',
    logo: '/logos/notion-calendar.png',
    link: 'https://notion.so/calendar',
    categories: ['calendar', 'all-in-one'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'bear-notes',
    name: 'Bear Notes',
    description: 'Bear Notes is a minimal, markdown note-taking application perfect for iOS and Mac.',
    logo: '/logos/bear-notes.png',
    link: 'https://bear.app',
    categories: ['note-taking', 'markdown'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'notesnook',
    name: 'Notesnook',
    description: 'Notesnook is an E2E note taking application with a focus of privacy and security.',
    logo: '/logos/notesnook.png',
    link: 'https://notesnook.com',
    categories: ['note-taking', 'encrypted-apps'],
    platforms: ['web', 'mac', 'windows', 'linux', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'microsoft-loop',
    name: 'Microsoft Loop',
    description: 'Microsoft Loop combines pages, workspaces & something called Loop Components.',
    logo: '/logos/microsoft-loop.png',
    link: 'https://loop.microsoft.com',
    categories: ['note-taking', 'team-knowledge', 'document-editing'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Jira is an issue tracking software for projects built by Atlassian.',
    logo: '/logos/jira.png',
    link: 'https://www.atlassian.com/software/jira',
    categories: ['project-management', 'agile-tools'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['manager', 'developer', 'operations'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud', 'on-premise'],
    industries: ['development'],
    customizability: 'high'
  },
  {
    id: 'fantastical',
    name: 'Fantastical',
    description: 'Fantastical is a calendar app that handles events, tasks & meeting scheduling in one.',
    logo: '/logos/fantastical.png',
    link: 'https://flexibits.com/fantastical',
    categories: ['calendar', 'todo-list', 'meeting-schedulers'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'streaks',
    name: 'Streaks',
    description: 'A habit tracker with an intuitive interface for iOS and Apple devices.',
    logo: '/logos/streaks.png',
    link: 'https://streaks.app',
    categories: ['habit-tracking'],
    platforms: ['ios', 'mac', 'watch'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'brite',
    name: 'Brite',
    description: 'Brite wants to be your daily planner app for tasks, calendar & habit tracking in one.',
    logo: '/logos/brite.png',
    link: 'https://brite.app',
    categories: ['daily-planners', 'todo-list', 'habit-tracking'],
    platforms: ['ios', 'mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'logseq',
    name: 'Logseq',
    description: 'Logseq is a note-taking application with whiteboards, networked thought & graph.',
    logo: '/logos/logseq.png',
    link: 'https://logseq.com',
    categories: ['note-taking', 'pkm-apps', 'whiteboard'],
    platforms: ['mac', 'windows', 'linux', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['local'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'mymind',
    name: 'mymind',
    description: 'If Pinterest and Google Keep had a baby, it would be MyMind for notes and ideas.',
    logo: '/logos/mymind.png',
    link: 'https://mymind.com',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web', 'ios', 'chrome'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    description: 'Google Docs is a document collaboration tool used for creating sharable documents.',
    logo: '/logos/google-docs.png',
    link: 'https://docs.google.com',
    categories: ['document-editing', 'team-knowledge'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'endel',
    name: 'Endel',
    description: 'Endel improves your focus by blocking apps and building soundscapes using data.',
    logo: '/logos/endel.png',
    link: 'https://endel.io',
    categories: ['focus-apps', 'mindful'],
    platforms: ['ios', 'android', 'mac', 'windows'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'rise-calendar',
    name: 'Rise Calendar',
    description: 'Rise Calendar wants to help you better focus your time at work with their calendar.',
    logo: '/logos/rise-calendar.png',
    link: 'https://risecalendar.com',
    categories: ['calendar', 'focus-apps'],
    platforms: ['mac', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'sublime',
    name: 'Sublime',
    description: 'Sublime allows you to save your ideas, PDFs, links, videos and highlights.',
    logo: '/logos/sublime.png',
    link: 'https://sublime.app',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'affine',
    name: 'AFFiNE Pro',
    description: 'AFFiNE Pro is a open source note-taking app coming after the likes of Notion.',
    logo: '/logos/affine.png',
    link: 'https://affine.pro',
    categories: ['note-taking', 'whiteboard', 'document-editing'],
    platforms: ['web', 'mac', 'windows', 'linux'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud', 'local'],
    industries: ['all'],
    customizability: 'high',
    isRisingStar: true
  },
  {
    id: 'vimcal',
    name: 'Vimcal',
    description: 'Vimcal is an AI-powered calendar app that wants to be fast & easy to manage calendar.',
    logo: '/logos/vimcal.png',
    link: 'https://vimcal.com',
    categories: ['calendar', 'ai-tools', 'meeting-schedulers'],
    platforms: ['web', 'mac', 'ios'],
    pricing: ['subscription'],
    roles: ['manager', 'entrepreneur'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'fabulous',
    name: 'Fabulous',
    description: 'Fabulous is a habit tracking app with deep work sounds & coaching lessons.',
    logo: '/logos/fabulous.png',
    link: 'https://www.thefabulous.co/',
    categories: ['habit-tracking', 'mindful', 'focus-apps'],
    platforms: ['ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'clockwise-ai',
    name: 'Clockwise AI',
    description: 'Clockwise is an AI calendar and scheduling assistant used for teams to manage time.',
    logo: '/logos/clockwise-ai.png',
    link: 'https://www.getclockwise.com/',
    categories: ['calendar', 'ai-tools', 'meeting-schedulers'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'entrepreneur'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'meistertask',
    name: 'MeisterTask',
    description: 'MeisterTask is a project management and task management software for teams.',
    logo: '/logos/meistertask.png',
    link: 'https://www.meistertask.com/',
    categories: ['project-management', 'todo-list', 'team-knowledge'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'flown',
    name: 'FLOWN',
    description: 'FLOWN wants to help you focus with sessions in small groups to boost accountability.',
    logo: '/logos/flown.png',
    link: 'https://flown.com/',
    categories: ['focus-apps', 'mindful'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'paced',
    name: 'Paced',
    description: 'Paced is a to-do list app for scheduling your day and routines with focus & energy.',
    logo: '/logos/paced.png',
    link: 'https://www.paced.com/',
    categories: ['todo-list', 'daily-planners', 'focus-apps'],
    platforms: ['web', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'actions-by-moleskine',
    name: 'Actions by Moleskine',
    description: 'Moleskine Actions wants to be your base for lists, to-dos and planning tasks ahead.',
    logo: '/logos/actions-by-moleskine.png',
    link: 'https://moleskinestudio.com/actions/',
    categories: ['todo-list', 'daily-planners'],
    platforms: ['ios', 'mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'beedone',
    name: 'BeeDone',
    description: 'BeeDone wants to gamify your task management using AI to plan your week.',
    logo: '/logos/beedone.png',
    link: 'https://www.beedone.app/',
    categories: ['todo-list', 'ai-tools', 'habit-tracking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'upbase',
    name: 'Upbase',
    description: 'Upbase wants to be your small teams place to manage projects but also yourself too.',
    logo: '/logos/upbase.png',
    link: 'https://upbase.io/',
    categories: ['project-management', 'team-knowledge'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'entrepreneur'],
    userTypes: ['small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'beforesunset-ai',
    name: 'BeforeSunset AI',
    description: 'BeforeSunset AI helps users create routines, plan their day and track schedules.',
    logo: '/logos/beforesunset-ai.png',
    link: 'https://www.beforesunset.ai/',
    categories: ['daily-planners', 'ai-tools', 'todo-list'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'ChatGPT is a text and voice based chatbot developed by OpenAI used by millions.',
    logo: '/logos/chatgpt.png',
    link: 'https://chat.openai.com/',
    categories: ['ai-tools'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'habitica',
    name: 'Habitica',
    description: 'Habitica wants to gamify your habit tracking with XP, collectables & more.',
    logo: '/logos/habitica.png',
    link: 'https://habitica.com/',
    categories: ['habit-tracking', 'todo-list'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'due',
    name: 'Due',
    description: 'Due is a reminder tool to help you manage and complete tasks.',
    logo: '/logos/due.png',
    link: 'https://www.dueapp.com/',
    categories: ['todo-list', 'time-tracking'],
    platforms: ['ios', 'mac'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'A no-code workspace for collaboration and organisation amongst teams.',
    logo: '/logos/airtable.png',
    link: 'https://airtable.com/',
    categories: ['no-code', 'project-management', 'team-knowledge'],
    platforms: ['web', 'ios', 'android', 'mac'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'reclaim-ai',
    name: 'Reclaim AI',
    description: 'Reclaim AI is perfect for smart calendar app for teams to optimise schedules.',
    logo: '/logos/reclaim-ai.png',
    link: 'https://reclaim.ai/',
    categories: ['calendar', 'ai-tools', 'meeting-schedulers'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'entrepreneur'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'nozbe',
    name: 'Nozbe',
    description: 'Nozbe is a simple project management tool to manage work and life tasks.',
    logo: '/logos/nozbe.png',
    link: 'https://nozbe.com/',
    categories: ['project-management', 'todo-list'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'lazy',
    name: 'Lazy',
    description: 'Lazy is a capture tool that can be used to quick capture ideas, bookmarks & uses AI.',
    logo: '/logos/lazy.png',
    link: 'https://lazy.so/',
    categories: ['note-taking', 'ai-tools'],
    platforms: ['web', 'chrome'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'supernotes',
    name: 'Supernotes',
    description: 'A beautifully-designed note-taking tool that was originally developed for students.',
    logo: '/logos/supernotes.png',
    link: 'https://supernotes.app',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['student', 'all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['education', 'all'],
    customizability: 'high'
  },
  {
    id: 'perplexity-ai',
    name: 'Perplexity AI',
    description: 'Perplexity is an AI search engine for researching and gathering information using AI.',
    logo: '/logos/perplexity-ai.png',
    link: 'https://perplexity.ai',
    categories: ['ai-tools'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'process-street',
    name: 'Process Street',
    description: 'Process Street is an AI workflow automation tool for tasks, projects and teams.',
    logo: '/logos/process-street.png',
    link: 'https://process.st',
    categories: ['workflow-auto', 'project-management'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'operations'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Gmail is an email tool offered free by Google with filters, labels & mobile apps too.',
    logo: '/logos/gmail.png',
    link: 'https://gmail.com',
    categories: ['email'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'glasp',
    name: 'Glasp',
    description: 'Glasp is a web & PDF highlighting tool that works with Google Chrome & Safari.',
    logo: '/logos/glasp.png',
    link: 'https://glasp.co',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['chrome'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'microsoft-excel',
    name: 'Microsoft Excel',
    description: 'Microsoft Excel is for spreadsheets and data to help you manage information.',
    logo: '/logos/microsoft-excel.png',
    link: 'https://www.microsoft.com/excel',
    categories: ['spreadsheet'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud', 'local'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'microsoft-todo',
    name: 'Microsoft To-Do',
    description: 'Microsoft To-Do is a to-do list application that can be used to manage lists & tasks.',
    logo: '/logos/microsoft-todo.png',
    link: 'https://todo.microsoft.com',
    categories: ['todo-list'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'pocnote',
    name: 'Pocnote',
    description: 'Pocnote is an AI assistant for note-taking with voice notes & transcription.',
    logo: '/logos/pocnote.png',
    link: 'https://pocnote.com',
    categories: ['note-taking', 'ai-tools'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'apple-mail',
    name: 'Apple Mail',
    description: 'Apple Mail is the native email client that is available for all Apple users.',
    logo: '/logos/apple-mail.png',
    link: 'https://support.apple.com/mail',
    categories: ['email'],
    platforms: ['mac', 'ios'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['local'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'cozi',
    name: 'Cozi',
    description: 'Get all your family\'s calendar with to-do lists to schedule on the same page.',
    logo: '/logos/cozi.png',
    link: 'https://cozi.com',
    categories: ['calendar', 'todo-list'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'noteshelf',
    name: 'Noteshelf',
    description: 'A note-taking application with range of features and customisation abilities.',
    logo: '/logos/noteshelf.png',
    link: 'https://noteshelf.net',
    categories: ['note-taking'],
    platforms: ['ios', 'android', 'mac'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'mem',
    name: 'Mem',
    description: 'Mem is an AI focused note-taking application with no folders and AI-chat for notes.',
    logo: '/logos/mem.png',
    link: 'https://mem.ai',
    categories: ['note-taking', 'ai-tools'],
    platforms: ['web', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high',
    isRisingStar: true
  },
  {
    id: 'tweek',
    name: 'Tweek',
    description: 'Tweek Calendar wants to help you manage calendar & tasks in a light way.',
    logo: '/logos/tweek.png',
    link: 'https://tweek.so',
    categories: ['calendar', 'todo-list'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'raycast',
    name: 'Raycast',
    description: 'Raycast is a macOS launcher designed for saving time and speeding up your commands.',
    logo: '/logos/raycast.png',
    link: 'https://raycast.com',
    categories: ['productivity'],
    platforms: ['mac'],
    pricing: ['free', 'subscription'],
    roles: ['developer', 'all'],
    userTypes: ['individual'],
    deployments: ['local'],
    industries: ['all'],
    customizability: 'high',
    isEditorChoice: true
  },
  {
    id: 'agenda-notes',
    name: 'Agenda Notes',
    description: 'Agenda Notes is a note-taking app with calendar focus for managing dates & notes.',
    logo: '/logos/agenda-notes.png',
    link: 'https://agenda.com',
    categories: ['note-taking', 'calendar'],
    platforms: ['mac', 'ios'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Co-ordinate meetings, events and appointments in Google\'s free, go-to calendar app.',
    logo: '/logos/google-calendar.png',
    link: 'https://calendar.google.com',
    categories: ['calendar', 'meeting-schedulers'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'hey-email',
    name: 'HEY Email',
    description: 'HEY Email is a productivity-intense email app with a set system on handling emails.',
    logo: '/logos/hey-email.png',
    link: 'https://hey.com',
    categories: ['email'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isEditorChoice: true
  },
  {
    id: 'fabric',
    name: 'Fabric',
    description: 'Fabric is a universal workspace and smart organizer for all your notes & files.',
    logo: '/logos/fabric.png',
    link: 'https://fabric.so',
    categories: ['note-taking', 'file-management'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'ping',
    name: 'Ping',
    description: 'Ping is an AI-powered to-do app for managing tasks and boosting productivity.',
    logo: 'https://ping.app/assets/logo.png',
    link: 'https://ping.app',
    categories: ['todo-list', 'ai-tools'],
    platforms: ['web', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Google Sheets is an Excel alternative for those who want to build using spreadsheets.',
    logo: 'https://ssl.gstatic.com/docs/spreadsheets/favicon3.ico',
    link: 'https://sheets.google.com',
    categories: ['spreadsheet'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'google-keep',
    name: 'Google Keep',
    description: 'Google Keep is the digital version of Post-it Notes created by the folks at Google.',
    logo: 'https://ssl.gstatic.com/keep/icon_2020q4v2_128.png',
    link: 'https://keep.google.com',
    categories: ['note-taking'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'goodnotes',
    name: 'Goodnotes',
    description: 'Goodnotes is a iPad focused note-taking application with AI and handwriting tools.',
    logo: '/logos/goodnotes.png',
    link: 'https://goodnotes.com',
    categories: ['note-taking'],
    platforms: ['ios', 'mac'],
    pricing: ['one-time'],
    roles: ['student', 'all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['education', 'all'],
    customizability: 'high'
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Discord is a chat & team communication for communicating with customization.',
    logo: 'https://assets.discord.com/images/847541504914fd33810e70a0ea73177e.ico',
    link: 'https://discord.com',
    categories: ['team-communication'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows', 'linux'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'readwise',
    name: 'Readwise',
    description: 'Readwise wants to be your place to store tweets, Kindle highlights & more for later.',
    logo: '/logos/readwise.png',
    link: 'https://readwise.io',
    categories: ['note-taking', 'pkm-apps'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'microsoft-onenote',
    name: 'Microsoft OneNote',
    description: 'Note-taking and organising app perfect for students, academics and general notes.',
    logo: '/logos/microsoft-onenote.png',
    link: 'https://onenote.com',
    categories: ['note-taking'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'stoic',
    name: 'Stoic',
    description: 'Stoic is a journal app for practicing journaling, habit tracking and meditation.',
    logo: 'https://stoicapp.com/assets/logo.png',
    link: 'https://stoicapp.com',
    categories: ['journaling', 'habit-tracking', 'mindful'],
    platforms: ['ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'daylio',
    name: 'Daylio',
    description: 'Daylio is a self care diary, goal tracker, and mood tracker all in one.',
    logo: 'https://daylio.app/assets/logo.png',
    link: 'https://daylio.app',
    categories: ['journaling', 'habit-tracking', 'mindful'],
    platforms: ['ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Zapier is an automation tool that helps you connect tools together with AI and more.',
    logo: 'https://cdn.zapier.com/zapier/images/favicon.ico',
    link: 'https://zapier.com',
    categories: ['workflow-auto', 'ai-tools'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'tactiq',
    name: 'Tactiq',
    description: 'Tactiq is an AI meeting note tool for Google Meet, Microsoft Teams & Zoom.',
    logo: '/logos/tactiq.png',
    link: 'https://tactiq.io',
    categories: ['note-taking', 'ai-tools'],
    platforms: ['chrome'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'everyday-habits',
    name: 'Everyday Habits',
    description: 'Everyday Habits helps you track habits, streaks and success with your daily habits.',
    logo: 'https://everydayhabits.app/assets/logo.png',
    link: 'https://everydayhabits.app',
    categories: ['habit-tracking'],
    platforms: ['ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'day-one',
    name: 'Day One',
    description: 'Day One is a journaling app used to capture memories and write your journal.',
    logo: '/logos/day-one.png',
    link: 'https://dayoneapp.com',
    categories: ['journaling'],
    platforms: ['ios', 'mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'sorted3',
    name: 'Sorted 3',
    description: 'Sorted 3 manages your tasks and time efficiently using a timeline like to-do list.',
    logo: '/logos/sorted3.png',
    link: 'https://sorted.app',
    categories: ['todo-list', 'daily-planners', 'time-tracking'],
    platforms: ['ios', 'mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'mimestream',
    name: 'Mimestream',
    description: 'Mimestream takes your Gmail to the next-level with a clean, native macOS email app.',
    logo: '/logos/mimestream.png',
    link: 'https://mimestream.com',
    categories: ['email'],
    platforms: ['mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'zoho-crm',
    name: 'Zoho CRM',
    description: 'Zoho CRM is a top-rated sales CRM that uses AI for better conversions.',
    logo: '/logos/zoho-crm.png',
    link: 'https://www.zoho.com/crm',
    categories: ['crm-software', 'ai-tools'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['manager', 'sales'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['sales'],
    customizability: 'high'
  },
  {
    id: 'zoom',
    name: 'Zoom',
    description: 'The all-in-one meetings, documents, whiteboard, mail and calendar hub.',
    logo: '/logos/zoom.png',
    link: 'https://zoom.us',
    categories: ['team-communication', 'remote-work', 'whiteboard'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'notability',
    name: 'Notability',
    description: 'A popular with students, visual notes app with tons of Apple Pencil abilities.',
    logo: '/logos/notability.png',
    link: 'https://notability.com',
    categories: ['note-taking'],
    platforms: ['ios', 'mac'],
    pricing: ['one-time'],
    roles: ['student', 'all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['education', 'all'],
    customizability: 'high'
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Figma is a design platform that millions use to create designs and creative daily.',
    logo: '/logos/figma.png',
    link: 'https://figma.com',
    categories: ['design', 'whiteboard', 'team-knowledge'],
    platforms: ['web', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['designer', 'all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'godspeed',
    name: 'Godspeed',
    description: 'Godspeed is one of the fastest to-do apps on the market for keyboard lovers.',
    logo: '/logos/godspeed.png',
    link: 'https://godspeed.systems',
    categories: ['todo-list'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'wispr-flow',
    name: 'Wispr Flow',
    description: 'Wispr Flow helps you manage your tasks and workflows efficiently.',
    logo: 'https://wisprflow.com/logo.png',
    link: 'https://wisprflow.com',
    categories: ['ai-tools', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'clipbook',
    name: 'ClipBook',
    description: 'ClipBook is your digital clipboard manager.',
    logo: 'https://clipbook.app/logo.png',
    link: 'https://clipbook.app',
    categories: ['productivity'],
    platforms: ['mac'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['local'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'fonti',
    name: 'Fonti',
    description: 'Fonti helps you manage and organize your fonts.',
    logo: 'https://fonti.app/logo.png',
    link: 'https://fonti.app',
    categories: ['design'],
    platforms: ['ios'],
    pricing: ['subscription'],
    roles: ['designer'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low',
    isNew: true
  },
  {
    id: 'shortwave-email',
    name: 'Shortwave Email',
    description: 'Shortwave Email is a fast email app with AI assistance and focus first features.',
    logo: '/logos/shortwave-email.png',
    link: 'https://shortwave.com',
    categories: ['email', 'ai-tools'],
    platforms: ['web', 'ios'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'Grammarly is a communication assistant for writing better text and documents.',
    logo: '/logos/grammarly.png',
    link: 'https://grammarly.com',
    categories: ['writing-tools', 'ai-tools'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'calendar-366',
    name: 'Calendar 366',
    description: 'Calendar 366 is a powerful calendar app for macOS.',
    logo: 'https://calendar366.com/images/logo.png',
    link: 'https://calendar366.com',
    categories: ['calendar', 'todo-list'],
    platforms: ['mac', 'ios'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'kinopio',
    name: 'Kinopio',
    description: 'A fun, interactive spacial thinking for new ideas, connecting notes and problems.',
    logo: '/logos/kinopio.png',
    link: 'https://kinopio.club',
    categories: ['mind-mapping', 'note-taking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'benji',
    name: 'Benji',
    description: 'Benji is your AI-powered productivity assistant.',
    logo: 'https://usebenji.com/logo.png',
    link: 'https://usebenji.com',
    categories: ['calendar', 'todo-list', 'habit-tracking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'whole',
    name: 'Whole',
    description: 'Whole is a habit tracking app that wants to help you check-in and track your mood.',
    logo: '/logos/whole.png',
    link: 'https://whole.app',
    categories: ['habit-tracking', 'mindful'],
    platforms: ['ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'freedom',
    name: 'Freedom',
    description: 'Freedom blocks websites and distractions to enter deeper focus and more productive.',
    logo: '/logos/freedom.png',
    link: 'https://freedom.to',
    categories: ['focus-apps', 'productivity'],
    platforms: ['mac', 'windows', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'ohyeah',
    name: 'OhYeah',
    description: 'OhYeah wants to be your to-do list, notes and calendar in one location.',
    logo: '/logos/ohyeah.png',
    link: 'https://ohyeah.so',
    categories: ['todo-list', 'note-taking', 'calendar'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'sync',
    name: 'Sync',
    description: 'Sync.com wants to be your cloud storage for secure file storage online.',
    logo: '/logos/sync.png',
    link: 'https://sync.com',
    categories: ['file-management', 'cloud-storage'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: '1password',
    name: '1Password',
    description: '1Password is a password storage software for teams & individuals.',
    logo: '/logos/1password.png',
    link: 'https://1password.com',
    categories: ['password-managers', 'security'],
    platforms: ['mac', 'windows', 'ios', 'android', 'web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'llama-life',
    name: 'Llama Life',
    description: 'Llama Life is an ADHD planner app & to-do app and lightweight extension for tasks.',
    logo: '/logos/llama-life.png',
    link: 'https://llamalife.co',
    categories: ['todo-list', 'daily-planners'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'keeping',
    name: 'Keeping',
    description: 'Keeping is a shared inbox tool that connects with Google Workspace for collaboration',
    logo: '/logos/keeping.png',
    link: 'https://keeping.com',
    categories: ['shared-inbox', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'help-scout',
    name: 'Help Scout',
    description: 'Help Scout is a shared inbox software with a chatbot feature & knowledge base.',
    logo: '/logos/help-scout.png',
    link: 'https://helpscout.com',
    categories: ['shared-inbox', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'focus-bear',
    name: 'Focus Bear',
    description: 'Focus Bear blocks websites & helps you get intentional about what you\'re working on.',
    logo: '/logos/focus-bear.png',
    link: 'https://focusbear.app',
    categories: ['focus-apps', 'productivity'],
    platforms: ['mac', 'windows'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['local'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'week-plan',
    name: 'Week Plan',
    description: 'Week Plan wants to the place to organize your week, schedule & life plans ahead.',
    logo: '/logos/week-plan.png',
    link: 'https://weekplan.net',
    categories: ['daily-planners', 'todo-list'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'higher-goals',
    name: 'Higher Goals',
    description: 'Higher Goals uses SMART goals and visualisation to create new habits.',
    logo: '/logos/higher-goals.png',
    link: 'https://highergoals.app',
    categories: ['habit-tracking', 'daily-planners'],
    platforms: ['web', 'ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'five-minute-journal',
    name: 'Five Minute Journal',
    description: 'Expand your mind with a journaling system in just five minutes every single day.',
    logo: '/logos/five-minute-journal.png',
    link: 'https://fiveminutejournal.com',
    categories: ['journaling', 'mindful'],
    platforms: ['ios', 'android'],
    pricing: ['one-time'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low',
    isRisingStar: true
  },
  {
    id: 'simplenote',
    name: 'Simplenote',
    description: 'Simplenote is an efficient light note-taking application and a Bear alternative.',
    logo: '/logos/simplenote.png',
    link: 'https://simplenote.com',
    categories: ['note-taking'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android', 'linux'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'loom',
    name: 'Loom',
    description: 'Loom is an async method of communication with your team through video recordings.',
    logo: '/logos/loom.png',
    link: 'https://loom.com',
    categories: ['team-communication', 'remote-work'],
    platforms: ['web', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'pdf-ai',
    name: 'PDF.ai',
    description: 'PDF.ai is a tool for chatting with documents to ask questions and summarise PDFs.',
    logo: '/logos/pdf-ai.png',
    link: 'https://pdf.ai',
    categories: ['ai-tools', 'document-editing'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'calendar-com',
    name: 'Calendar.com',
    description: 'Calendar.com wants to be a place for your team to schedule meetings with others.',
    logo: '/logos/calendar-com.png',
    link: 'https://calendar.com',
    categories: ['calendar', 'meeting-schedulers'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'redactable',
    name: 'Redactable',
    description: 'Redactable is a automatic redaction software for legal, finance, HR & more.',
    logo: '/logos/redactable.png',
    link: 'https://redactable.com',
    categories: ['document-editing', 'ai-tools'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'mapify',
    name: 'Mapify',
    description: 'Mapify is an AI mind mapping tool designed for individuals to create easy mind maps.',
    logo: 'https://logo.clearbit.com/mapify.ai',
    link: 'https://mapify.ai',
    categories: ['mind-mapping', 'ai-tools'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isNew: true
  },
  {
    id: 'karbon',
    name: 'Karbon',
    description: 'Karbon is a project management software designed & built for accounting practices.',
    logo: 'https://logo.clearbit.com/karbonhq.com',
    link: 'https://karbonhq.com',
    categories: ['project-management', 'team-knowledge'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'operations'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'whereby',
    name: 'Whereby',
    description: 'Whereby is a team video collaboration tool for meetings & designed to be easy to use.',
    logo: 'https://logo.clearbit.com/whereby.com',
    link: 'https://whereby.com',
    categories: ['team-communication', 'remote-work'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'guru',
    name: 'Guru',
    description: 'Guru is a AI-powered knowledge management system for your team\'s brain.',
    logo: 'https://logo.clearbit.com/getguru.com',
    link: 'https://getguru.com',
    categories: ['team-knowledge', 'ai-tools'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'sana-ai',
    name: 'Sana AI',
    description: 'Sana AI is a meeting note-taking tool with AI agents & integrations.',
    logo: 'https://logo.clearbit.com/sana.ai',
    link: 'https://sana.ai',
    categories: ['note-taking', 'ai-tools', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isNew: true
  },
  {
    id: 'bluedot-ai',
    name: 'Bluedot AI',
    description: 'Bluedot is an AI meeting note-taking tool that connects with Google Meet.',
    logo: 'https://logo.clearbit.com/bluedot.ai',
    link: 'https://bluedot.ai',
    categories: ['note-taking', 'ai-tools', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Twilio is a cloud communication platform for voice, SMS, and APIs.',
    logo: 'https://logo.clearbit.com/twilio.com',
    link: 'https://twilio.com',
    categories: ['team-communication', 'workflow-auto'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['developer', 'operations'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'commusoft',
    name: 'Commusoft',
    description: 'Commusoft is a field service software for job management and customer support.',
    logo: 'https://logo.clearbit.com/commusoft.com',
    link: 'https://commusoft.com',
    categories: ['project-management', 'crm-software'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['manager', 'operations'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'circle',
    name: 'Circle',
    description: 'Circle is a community platform for building and managing online groups.',
    logo: 'https://logo.clearbit.com/circle.so',
    link: 'https://circle.so',
    categories: ['team-communication', 'community'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'napkin-ai',
    name: 'Napkin AI',
    description: 'Napkin AI is an idea management tool using AI to organize and connect notes.',
    logo: 'https://logo.clearbit.com/napkin.ai',
    link: 'https://napkin.ai',
    categories: ['note-taking', 'ai-tools', 'mind-mapping'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isNew: true
  },
  {
    id: 'jasper-ai',
    name: 'Jasper AI',
    description: 'Jasper AI is a content creation tool for generating AI-written marketing copy.',
    logo: 'https://logo.clearbit.com/jasper.ai',
    link: 'https://jasper.ai',
    categories: ['ai-tools', 'writing-tools'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['marketing'],
    customizability: 'high'
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'Descript is an all-in-one video and audio editing tool for creators.',
    logo: 'https://logo.clearbit.com/descript.com',
    link: 'https://descript.com',
    categories: ['video-editing', 'ai-tools'],
    platforms: ['mac', 'windows'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'exa-ai',
    name: 'Exa AI',
    description: 'Exa AI offers business-grade web search and crawling for any web data.',
    logo: '/logos/exa-ai.png',
    link: 'https://exa.ai',
    categories: ['ai-tools', 'research'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'windiary',
    name: 'WinDiary',
    description: 'WinDiary is a journaling app for tracking achievements and personal growth.',
    logo: '/logos/windiary.png',
    link: 'https://windiary.app',
    categories: ['journaling', 'habit-tracking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'mindsera',
    name: 'Mindsera',
    description: 'Mindsera is a self-coaching platform for personal growth and mental clarity.',
    logo: '/logos/mindsera.png',
    link: 'https://mindsera.com',
    categories: ['mindful', 'habit-tracking'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'buddy-punch',
    name: 'Buddy Punch',
    description: 'Buddy Punch is time tracking software for employee scheduling and payroll.',
    logo: 'https://logo.clearbit.com/buddypunch.com',
    link: 'https://buddypunch.com',
    categories: ['time-tracking', 'productivity'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'operations'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'glide',
    name: 'Glide',
    description: 'Glide is a no-code platform for creating custom apps from spreadsheets.',
    logo: 'https://logo.clearbit.com/glideapps.com',
    link: 'https://glideapps.com',
    categories: ['no-code', 'spreadsheet'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'contextminds',
    name: 'Contextminds',
    description: 'Contextminds is a writing companion that combines search, whiteboards & AI.',
    logo: 'https://logo.clearbit.com/contextminds.com',
    link: 'https://contextminds.com',
    categories: ['writing-tools', 'ai-tools', 'whiteboard'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isNew: true
  },
  {
    id: 'lucia',
    name: 'Lucia',
    description: 'Lucia is an AI voice agent that handles phone calls and nurtures leads.',
    logo: 'https://logo.clearbit.com/lucia.so',
    link: 'https://lucia.so',
    categories: ['ai-tools', 'crm-software'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['sales', 'manager'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['sales'],
    customizability: 'medium',
    isNew: true
  },
  {
    id: 'seline',
    name: 'Seline',
    description: 'Seline is a privacy-first Google Analytics platform for website & product analytics.',
    logo: 'https://logo.clearbit.com/seline.dev',
    link: 'https://seline.dev',
    categories: ['analytics', 'privacy'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['developer', 'manager'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'zencutter',
    name: 'Zencutter',
    description: 'ZenCutter is an all-in-one organizer for lists, calendar, plans & file management.',
    logo: 'https://logo.clearbit.com/zencutter.com',
    link: 'https://zencutter.com',
    categories: ['todo-list', 'calendar', 'file-management'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    description: 'WordPress is a platform for creating websites, blogs, and online stores with ease.',
    logo: 'https://logo.clearbit.com/wordpress.org',
    link: 'https://wordpress.org',
    categories: ['cms', 'website-builder'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud', 'self-hosted'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'google-forms',
    name: 'Google Forms',
    description: 'Google Forms is a form-building software developed by Google for individuals & teams.',
    logo: 'https://ssl.gstatic.com/docs/forms/favicon_qp2.ico',
    link: 'https://forms.google.com',
    categories: ['form-building'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'linkedin',
    name: 'Linkedin',
    description: 'linkedin is a platform for professional networking and job search.',
    logo: 'https://logo.clearbit.com/linkedin.com',
    link: 'https://linkedin.com',
    categories: ['professional-network', 'job-search'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Google Drive is a cloud storage service for file sharing and collaboration.',
    logo: 'https://ssl.gstatic.com/images/branding/product/2x/drive_2020q4_48dp.png',
    link: 'https://drive.google.com',
    categories: ['file-management', 'cloud-storage'],
    platforms: ['web', 'ios', 'android', 'mac', 'windows'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'paypal',
    name: 'PayPal',
    description: 'PayPal processes payments for e-commerce and manages POS, invoices & more.',
    logo: 'https://logo.clearbit.com/paypal.com',
    link: 'https://paypal.com',
    categories: ['payments', 'finance'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'microsoft-outlook',
    name: 'Microsoft Outlook',
    description: 'Microsoft Outlook is a popular email client developed and managed by Microsoft.',
    logo: 'https://logo.clearbit.com/outlook.com',
    link: 'https://outlook.com',
    categories: ['email', 'calendar'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'bing',
    name: 'Bing',
    description: 'Bing is a Microsoft-owned search engine offering web, image, and video results.',
    logo: 'https://logo.clearbit.com/bing.com',
    link: 'https://bing.com',
    categories: ['search-engine', 'ai-tools'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['free'],
    roles: ['all'],
    userTypes: ['all'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'kompas-ai',
    name: 'Kompas AI',
    description: 'Kompas AI is an AI chat for report generation to help condense research & insight.',
    logo: 'https://logo.clearbit.com/kompas.ai',
    link: 'https://kompas.ai',
    categories: ['ai-tools', 'research'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isNew: true
  },
  {
    id: 'nimbus-note',
    name: 'Nimbus Note',
    description: 'Nimbus notes is great for an all round note-taking experience similar to Evernote.',
    logo: 'https://logo.clearbit.com/nimbusweb.me',
    link: 'https://nimbusweb.me',
    categories: ['note-taking', 'document-editing'],
    platforms: ['web', 'mac', 'windows', 'ios', 'android'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'everlog',
    name: 'Everlog',
    description: 'A simple easy to use journal application, Everlog supports markdown formatting.',
    logo: 'https://logo.clearbit.com/everlog.app',
    link: 'https://everlog.app',
    categories: ['journaling', 'markdown'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'fireflies-ai',
    name: 'Fireflies AI',
    description: 'Fireflies AI wants to automate your meeting notes using AI using transcript & search.',
    logo: '/logos/fireflies-ai.png',
    link: 'https://fireflies.ai',
    categories: ['ai-tools', 'note-taking', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium',
    isRisingStar: true
  },
  {
    id: 'posture-pal',
    name: 'Posture Pal',
    description: 'Posture Pal connects with your Airpods to remind you to sit up straight.',
    logo: '/logos/posture-pal.png',
    link: 'https://posturepal.app',
    categories: ['health', 'productivity'],
    platforms: ['ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'bundleiq',
    name: 'bundleIQ',
    description: 'bundleIQ wants to be a AI research platform for distilling documentation & research.',
    logo: '/logos/bundleiq.png',
    link: 'https://bundleiq.com',
    categories: ['ai-tools', 'research', 'document-editing'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'aha',
    name: 'Aha!',
    description: 'Aha! is a place for product teams to build roadmaps from ideas to delivery.',
    logo: '/logos/aha.png',
    link: 'https://aha.io',
    categories: ['project-management', 'product-management'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['manager', 'product'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['product'],
    customizability: 'high'
  },
  {
    id: 'not-boring-vibes',
    name: 'Not Boring Vibes',
    description: 'A sleep, relax and focus soundtrack application that adjust to your daily life.',
    logo: '/logos/not-boring-vibes.png',
    link: 'https://notboringvibes.app',
    categories: ['focus-apps', 'mindful'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'balance',
    name: 'Balance',
    description: 'Balance is a time tracking app with a focus on work life balance and burnout.',
    logo: '/logos/balance.png',
    link: 'https://balance.so',
    categories: ['time-tracking', 'mindful', 'productivity'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'blinkist',
    name: 'Blinkist',
    description: 'Blinkist wants to be the quicker way to consume books and audio in one app.',
    logo: '/logos/blinkist.png',
    link: 'https://blinkist.com',
    categories: ['learning', 'productivity'],
    platforms: ['web', 'ios', 'android'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'make',
    name: 'Make',
    description: 'Make.com helps create automations between apps to solve problems.',
    logo: '/logos/make.png',
    link: 'https://make.com',
    categories: ['workflow-auto', 'productivity'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'ucal',
    name: 'uCal',
    description: 'uCal is a unique iOS calendar app that wants to help re-think how you browse events.',
    logo: '/logos/ucal.png',
    link: 'https://ucal.app',
    categories: ['calendar'],
    platforms: ['ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'kyugo',
    name: 'Kyugo',
    description: 'Improve your work life balance with Kyugo, your personal time assistant.',
    logo: '/logos/kyugo.png',
    link: 'https://kyugo.app',
    categories: ['time-tracking', 'productivity', 'mindful'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'blobby',
    name: 'Blobby',
    description: 'Blobby is your habit tracking pocket pal for making sure you complete daily habits.',
    logo: '/logos/blobby.png',
    link: 'https://blobby.app',
    categories: ['habit-tracking'],
    platforms: ['ios'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'low'
  },
  {
    id: 'lucidchart',
    name: 'LucidChart',
    description: 'LucidChart is a diagramming application for teams to collaborate and plan together.',
    logo: '/logos/lucidchart.png',
    link: 'https://lucidchart.com',
    categories: ['design', 'team-knowledge'],
    platforms: ['web'],
    pricing: ['free', 'subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'broadcast',
    name: 'Broadcast',
    description: 'Broadcast wants to create AI meeting notes for you using your chosen meeting tools.',
    logo: '/logos/broadcast.png',
    link: 'https://broadcast.app',
    categories: ['ai-tools', 'note-taking', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  },
  {
    id: 'mural',
    name: 'Mural',
    description: 'Use Mural as an addition to your video calls to collaborate and share ideas.',
    logo: '/logos/mural.png',
    link: 'https://mural.co',
    categories: ['whiteboard', 'team-communication'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'high'
  },
  {
    id: 'semrush',
    name: 'Semrush',
    description: 'Semrush is an SEO and content management tool for marketing professionals.',
    logo: '/logos/semrush.png',
    link: 'https://semrush.com',
    categories: ['marketing', 'seo'],
    platforms: ['web'],
    pricing: ['subscription'],
    roles: ['marketing', 'manager'],
    userTypes: ['small-business', 'mid-market', 'enterprise'],
    deployments: ['cloud'],
    industries: ['marketing'],
    customizability: 'high'
  },
  {
    id: 'dropshare',
    name: 'Dropshare',
    description: 'Dropshare wants to save you time by sharing files easily using a quick link creation.',
    logo: '/logos/dropshare.png',
    link: 'https://dropshare.app',
    categories: ['file-management', 'productivity'],
    platforms: ['mac'],
    pricing: ['subscription'],
    roles: ['all'],
    userTypes: ['individual', 'small-business'],
    deployments: ['cloud'],
    industries: ['all'],
    customizability: 'medium'
  }
]
};
